import React from 'react';
import { View, Button } from 'react-native';
import { Notifications } from 'react-native-notifications';

const Notification = () => {
    const handleNotificationPress = () => {
        // Trigger a local notification
        Notifications.postLocalNotification({
            title: "Local notification",
            body: "This notification was generated by the app!",
            identifier: "uniqueIdentifier",
            payload: {},
            sound: "default",
            badge: 1,
            type: "text", // Replace with the correct type
            thread: "threadIdentifier", // Replace with the correct thread identifier
            // Add any other required properties based on the library's documentation
        });
    };

    return (
        <View>
            {/* Your other UI components */}
            <Button title="Trigger Notification" onPress={handleNotificationPress} />
        </View>
    );
};

export default Notification;
